name: Build PDF

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX (XeLaTeX)
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          latexmk_use_xelatex: true

      - name: Rename output (optional)
        run: cp main.pdf Rapor.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v5
        with:
          name: report-pdf
          path: Rapor.pdf
